# Generated by Django 5.2.4 on 2025-09-10 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_latitude_project_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlogin',
            name='username',
        ),
        migrations.RemoveField(
            model_name='corporatelogin',
            name='username',
        ),
        migrations.RemoveField(
            model_name='ngologin',
            name='username',
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='email',
            field=models.EmailField(default='admin@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corporatelogin',
            name='email',
            field=models.EmailField(default='corporate@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngologin',
            name='email',
            field=models.EmailField(default='ngo@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
