# Generated by Django 5.2.4 on 2025-09-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mobiletoken'),
        ('api', '0004_remove_adminlogin_username_and_more'),
    ]

    operations = [
    ]
