# Generated by Django 5.2.4 on 2025-09-10 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_chain_issued_alter_project_status_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.FloatField()),
                ('previous_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('nonce', models.IntegerField()),
                ('hash', models.CharField(max_length=255)),
                ('raw', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='ChainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('kind', models.CharField(max_length=32)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='txs', to='api.chainblock')),
            ],
        ),
    ]
