# Generated by Django 5.2.4 on 2025-09-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
