# Generated by Django 5.2.4 on 2025-09-22 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_tender_tenderapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='admin_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='admin_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_reviewed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='field_area_measured',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Field measured area in hectares', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='field_images_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='field_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='field_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_verified_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='field_species_data',
            field=models.JSONField(blank=True, help_text='Field officer species data', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='field_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='final_approved_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final approved area in hectares', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='isro_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isro_verified_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='isro_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='isro_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='satellite_analysis_data',
            field=models.JSONField(blank=True, help_text='Satellite analysis results', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='satellite_area_measured',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Satellite measured area in hectares', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='satellite_images_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.DecimalField(decimal_places=2, help_text='Planned area in hectares', max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('field_data_submitted', 'Field Data Submitted'), ('satellite_data_submitted', 'Satellite Data Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='FieldDataSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateField()),
                ('hectare_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('soil_type', models.CharField(choices=[('sandy', 'Sandy'), ('clay', 'Clay'), ('loamy', 'Loamy'), ('muddy', 'Muddy'), ('rocky', 'Rocky')], max_length=100)),
                ('water_salinity', models.DecimalField(blank=True, decimal_places=1, help_text='Parts per thousand (ppt)', max_digits=5, null=True)),
                ('tidal_range', models.DecimalField(blank=True, decimal_places=1, help_text='Meters', max_digits=5, null=True)),
                ('species_data', models.JSONField(help_text='Array of species with name, count, and health status')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_submissions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_submissions', to='api.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='field_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image_type', models.CharField(choices=[('overview', 'Overview'), ('closeup', 'Close-up'), ('measurement', 'Measurement'), ('species', 'Species'), ('gps', 'GPS Location'), ('other', 'Other')], default='other', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('field_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.fielddatasubmission')),
            ],
        ),
        migrations.CreateModel(
            name='SatelliteImageSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('pre_project', 'Pre-Project (Baseline)'), ('during_project', 'During Project'), ('post_project', 'Post-Project'), ('monitoring', 'Monitoring')], max_length=50)),
                ('capture_date', models.DateField()),
                ('satellite_name', models.CharField(choices=[('cartosat', 'Cartosat-2'), ('resourcesat', 'ResourceSat-2'), ('risat', 'RISAT-1'), ('hypersat', 'HysIS'), ('landsat', 'Landsat-8'), ('sentinel', 'Sentinel-2'), ('other', 'Other')], max_length=100)),
                ('resolution', models.DecimalField(decimal_places=1, help_text='Spatial resolution in meters', max_digits=5)),
                ('north_bound', models.DecimalField(decimal_places=6, max_digits=9)),
                ('south_bound', models.DecimalField(decimal_places=6, max_digits=9)),
                ('east_bound', models.DecimalField(decimal_places=6, max_digits=9)),
                ('west_bound', models.DecimalField(decimal_places=6, max_digits=9)),
                ('measured_area', models.DecimalField(blank=True, decimal_places=2, help_text='Satellite measured area in hectares', max_digits=10, null=True)),
                ('vegetation_index', models.DecimalField(blank=True, decimal_places=3, help_text='NDVI or similar index', max_digits=5, null=True)),
                ('analysis_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isro_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_submissions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_submissions', to='api.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='satellite_images/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.satelliteimagesubmission')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ngo', 'NGO Representative'), ('corporate', 'Corporate User'), ('admin', 'System Administrator'), ('field_officer', 'Field Officer'), ('isro_admin', 'ISRO Administrator')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('certification', models.CharField(blank=True, help_text='Professional certification', max_length=255)),
                ('assigned_regions', models.JSONField(default=list, help_text='List of regions assigned to field officer')),
                ('clearance_level', models.CharField(blank=True, help_text='Security clearance level', max_length=50)),
                ('specialization', models.CharField(blank=True, help_text='Technical specialization', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
