# Generated by Django 5.2.4 on 2025-09-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_tenderv2_proposalv2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='budget_range',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tender',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='location_preference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='proposalv2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenderv2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
