# Generated by Django 5.2.4 on 2025-09-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_tender_budget_range_tender_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderapplication',
            name='offered_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenderapplication',
            name='price_per_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tenderapplication',
            name='project_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenderapplication',
            name='project_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenderapplication',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='tenders/proposals/'),
        ),
        migrations.AlterField(
            model_name='tenderapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Applied', 'Applied'), ('Allotted', 'Allotted'), ('Rejected', 'Rejected')], default='Pending', max_length=16),
        ),
    ]
