# Generated by Django 5.2.4 on 2025-12-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_tenderapplication_offered_credits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('network_type', models.CharField(choices=[('local', 'Local Development'), ('sepolia', 'Sepolia Testnet'), ('goerli', 'Goerli Testnet'), ('mainnet', 'Ethereum Mainnet')], max_length=20)),
                ('rpc_url', models.URLField(help_text='RPC endpoint URL')),
                ('chain_id', models.IntegerField()),
                ('carbon_token_address', models.CharField(blank=True, help_text='Carbon Credit Token contract address', max_length=42)),
                ('marketplace_address', models.CharField(blank=True, help_text='Marketplace contract address', max_length=42)),
                ('private_key', models.CharField(blank=True, help_text='Private key for contract interactions (keep secure!)', max_length=66)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AddField(
            model_name='chaintransaction',
            name='block_number',
            field=models.BigIntegerField(blank=True, help_text='Blockchain block number', null=True),
        ),
        migrations.AddField(
            model_name='chaintransaction',
            name='gas_used',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chaintransaction',
            name='tx_hash',
            field=models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=66),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_external',
            field=models.BooleanField(default=False, help_text='True if user provided their own wallet'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='private_key',
            field=models.CharField(blank=True, help_text='Encrypted private key (optional)', max_length=66),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=42, unique=True),
        ),
    ]
